### ISSUE TITLE
[Bug Report]: Server crashes loading Sounds mod

### ISSUE THREAD

**Issue by gregoryw3** [TeamAOF/Craftoria#448]
### Modpack Version

1.17.1

### Describe your issue.

During server boot it seems to try loading the Sounds mod and crashes.
I'm using itzg docker with the following config:

```yaml
services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: true
      ALLOW_FLIGHT: true
      MOD_PLATFORM: AUTO_CURSEFORGE
      # allocate from https://console.curseforge.com/ and set in .env file
      CF_API_KEY: key
      CF_SLUG: craftoria

      MEMORY: 12G
      CF_EXCLUDE_MODS: |
        737481
        363363
        394468
        986380
        844662
        568563
        915902
        690971
        455508
        1089803
        511319
        6253636
        925889
    volumes:
      # Use managed volume by default, but can change to a relative path like
      - ./data:/data
      # to use a host directory
      #- mc-data:/data
# volumes:
#  mc-data:
```

I tried to disable the mod from loading on server by adding these two mod id's:
- 6253636
- 925889

I think 925889 is the correct one but it didn't stop the server from loading the mod, so that's why I tried the CurseForge mod URL id.

### Crash Report

https://gist.github.com/gregoryw3/da4d4e8f89b788bcd9a72402cb51c6d5

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server
